-- Seed opcional do catalogo global de itens.
-- Execute depois da migration 20260622211000_items_catalog_hardening.sql.
-- Itens globais usam user_id null e ficam visiveis para todos os usuarios.

insert into public.items (
  user_id, nome, categoria, subcategoria, categoria_valor, credito_tier,
  espacos, espacos_texto, proficiencia, tipo_arma, empunhadura,
  dano, teste, critico, alcance, tipo_dano, especial,
  protecao_valor, defesa_bonus, rd, penalidade,
  descricao, bonus_pericia, acao_uso, custo_pe, dt, duracao, resistencia,
  requisitos, tags, fonte, oficial
) values
  -- Armas simples
  (null, 'Faca', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Leve', '1d4', 'Luta', '19', 'Curto', 'C', 'Ágil; arremessável.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Martelo', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Leve', '1d6', 'Luta', 'x2', null, 'I', null, null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Punhal', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Leve', '1d4', 'Luta', 'x3', null, 'P', 'Ágil.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Bastão', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Uma mão', '1d6/1d8', 'Luta', 'x2', null, 'I', null, null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Machete', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Uma mão', '1d6', 'Luta', '19', null, 'C', null, null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Lança', 'arma', 'simples', 0, 0, 1, null, 'Simples', 'Corpo a corpo', 'Uma mão', '1d6', 'Luta', 'x2', 'Curto', 'P', 'Arremessável.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Cajado', 'arma', 'simples', 0, 0, 2, null, 'Simples', 'Corpo a corpo', 'Duas mãos', '1d6/1d6', 'Luta', 'x2', null, 'I', 'Ágil.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples'], 'ordem-paranormal-cap3', true),
  (null, 'Arco', 'arma', 'simples', 0, 0, 2, null, 'Simples', 'Disparo', 'Duas mãos', '1d6', 'Pontaria', 'x3', 'Médio', 'P', 'Usa flechas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples','disparo'], 'ordem-paranormal-cap3', true),
  (null, 'Besta', 'arma', 'simples', 0, 0, 2, null, 'Simples', 'Disparo', 'Duas mãos', '1d8', 'Pontaria', '19', 'Médio', 'P', 'Usa flechas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples','disparo'], 'ordem-paranormal-cap3', true),
  (null, 'Pistola', 'arma', 'simples', 1, 1, 1, null, 'Simples', 'Fogo', 'Leve', '1d12', 'Pontaria', '18', 'Curto', 'B', 'Usa balas curtas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Revólver', 'arma', 'simples', 1, 1, 1, null, 'Simples', 'Fogo', 'Leve', '2d6', 'Pontaria', '19/x3', 'Curto', 'B', 'Usa balas curtas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Fuzil de caça', 'arma', 'simples', 1, 1, 2, null, 'Simples', 'Fogo', 'Duas mãos', '2d8', 'Pontaria', '19/x3', 'Médio', 'B', 'Usa balas longas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','simples','fogo'], 'ordem-paranormal-cap3', true),

  -- Armas taticas e pesadas
  (null, 'Machadinha', 'arma', 'tatica', 0, 0, 1, null, 'Tática', 'Corpo a corpo', 'Leve', '1d6', 'Luta', 'x3', 'Curto', 'C', 'Arremessável.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica'], 'ordem-paranormal-cap3', true),
  (null, 'Nunchaku', 'arma', 'tatica', 0, 0, 1, null, 'Tática', 'Corpo a corpo', 'Leve', '1d8', 'Luta', 'x2', null, 'I', 'Ágil.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica'], 'ordem-paranormal-cap3', true),
  (null, 'Espada', 'arma', 'tatica', 1, 1, 1, null, 'Tática', 'Corpo a corpo', 'Uma mão', '1d8/1d10', 'Luta', '19', null, 'C', null, null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica'], 'ordem-paranormal-cap3', true),
  (null, 'Katana', 'arma', 'tatica', 1, 1, 2, null, 'Tática', 'Corpo a corpo', 'Duas mãos', '1d10', 'Luta', '19', null, 'C', 'Ágil.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica'], 'ordem-paranormal-cap3', true),
  (null, 'Motosserra', 'arma', 'tatica', 1, 1, 2, null, 'Tática', 'Corpo a corpo', 'Duas mãos', '3d6', 'Luta', 'x2', null, 'C', 'Ao rolar 6 no dano, role um dado adicional; impõe penalidade em ataques.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica'], 'ordem-paranormal-cap3', true),
  (null, 'Submetralhadora', 'arma', 'tatica', 1, 1, 1, null, 'Tática', 'Fogo', 'Uma mão', '2d6', 'Pontaria', '19/x3', 'Curto', 'B', 'Automática; usa balas curtas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Espingarda', 'arma', 'tatica', 1, 1, 2, null, 'Tática', 'Fogo', 'Duas mãos', '4d6', 'Pontaria', 'x3', 'Curto', 'B', 'Usa cartuchos.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Fuzil de assalto', 'arma', 'tatica', 2, 2, 2, null, 'Tática', 'Fogo', 'Duas mãos', '2d10', 'Pontaria', '19/x3', 'Médio', 'B', 'Automático; usa balas longas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Fuzil de precisão', 'arma', 'tatica', 3, 3, 2, null, 'Tática', 'Fogo', 'Duas mãos', '2d10', 'Pontaria', '19/x3', 'Longo', 'B', 'Usa balas longas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','tatica','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Bazuca', 'arma', 'pesada', 3, 3, 2, null, 'Pesada', 'Fogo', 'Duas mãos', '10d8', 'Pontaria', 'x2', 'Médio', 'I', 'Usa foguete.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','pesada','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Lança-chamas', 'arma', 'pesada', 3, 3, 2, null, 'Pesada', 'Fogo', 'Duas mãos', '6d6', 'Pontaria', 'x2', 'Curto', 'Fogo', 'Usa combustível.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','pesada','fogo'], 'ordem-paranormal-cap3', true),
  (null, 'Metralhadora', 'arma', 'pesada', 2, 2, 2, null, 'Pesada', 'Fogo', 'Duas mãos', '2d12', 'Pontaria', '19/x3', 'Médio', 'B', 'Automática; usa balas longas.', null, null, null, null, null, null, null, null, null, null, null, null, array['arma','pesada','fogo'], 'ordem-paranormal-cap3', true),

  -- Municoes
  (null, 'Balas curtas', 'municao', 'municao', 0, 0, 1, null, null, null, null, null, null, null, null, null, 'Usada por pistolas, revólveres e submetralhadoras.', null, null, null, null, null, null, null, null, null, '2 cenas', null, null, array['municao'], 'ordem-paranormal-cap3', true),
  (null, 'Balas longas', 'municao', 'municao', 1, 1, 1, null, null, null, null, null, null, null, null, null, 'Usada por fuzis e metralhadoras.', null, null, null, null, null, null, null, null, null, '1 cena', null, null, array['municao'], 'ordem-paranormal-cap3', true),
  (null, 'Cartuchos', 'municao', 'municao', 1, 1, 1, null, null, null, null, null, null, null, null, null, 'Usados por espingardas.', null, null, null, null, null, null, null, null, null, '1 cena', null, null, array['municao'], 'ordem-paranormal-cap3', true),
  (null, 'Flechas', 'municao', 'municao', 0, 0, 1, null, null, null, null, null, null, null, null, null, 'Usadas por arcos e bestas.', null, null, null, null, null, null, null, null, null, '1 missão', null, null, array['municao'], 'ordem-paranormal-cap3', true),
  (null, 'Foguete', 'municao', 'municao', 1, 1, 1, null, null, null, null, null, null, null, null, null, 'Usado por bazucas; dura um disparo.', null, null, null, null, null, null, null, null, null, '1 disparo', null, null, array['municao'], 'ordem-paranormal-cap3', true),

  -- Protecoes
  (null, 'Proteção leve', 'protecao', 'leve', 1, 1, 2, null, null, null, null, null, null, null, null, null, null, '+5', 5, null, null, null, null, null, null, null, null, null, null, array['protecao'], 'ordem-paranormal-cap3', true),
  (null, 'Proteção pesada', 'protecao', 'pesada', 2, 2, 5, null, null, null, null, null, null, null, null, null, null, '+10', 10, 'Balístico, corte, impacto e perfuração 2', '-5 em perícias afetadas por carga', null, null, null, null, null, null, null, null, array['protecao'], 'ordem-paranormal-cap3', true),
  (null, 'Escudo', 'protecao', 'escudo', 1, 1, 2, null, null, null, null, null, null, null, null, null, null, '+2', 2, null, null, 'Precisa ser empunhado em uma mão.', null, null, null, null, null, null, null, array['protecao','escudo'], 'ordem-paranormal-cap3', true),

  -- Equipamentos gerais
  (null, 'Kit de perícia', 'geral', 'acessorio', 0, 0, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ferramentas necessárias para certas perícias.', null, null, null, null, null, null, 'Escolha a perícia ao requisitar.', array['acessorio'], 'ordem-paranormal-cap3', true),
  (null, 'Utensílio', 'geral', 'acessorio', 1, 1, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Item comum com utilidade específica.', '+2 em uma perícia aprovada', null, null, null, null, null, 'Não vale para Luta ou Pontaria.', array['acessorio'], 'ordem-paranormal-cap3', true),
  (null, 'Vestimenta', 'geral', 'acessorio', 1, 1, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Peça de roupa com benefício situacional.', '+2 em uma perícia aprovada', 'Completa para vestir ou despir', null, null, null, null, 'Não vale para Luta ou Pontaria.', array['acessorio'], 'ordem-paranormal-cap3', true),
  (null, 'Granada de atordoamento', 'geral', 'explosivo', 0, 0, 1, null, null, null, null, null, null, null, 'Médio / raio 6m', null, 'Atordoa por 1 rodada.', null, null, null, null, null, null, 'Padrão', null, 'Fortitude DT Agi reduz', '1 rodada', null, null, array['explosivo'], 'ordem-paranormal-cap3', true),
  (null, 'Granada de fragmentação', 'geral', 'explosivo', 1, 1, 1, null, null, null, null, '8d6', null, null, 'Médio / raio 6m', 'P', null, null, null, null, null, null, null, 'Padrão', null, 'Reflexos DT Agi reduz à metade', null, null, null, array['explosivo'], 'ordem-paranormal-cap3', true),
  (null, 'Granada de fumaça', 'geral', 'explosivo', 0, 0, 1, null, null, null, null, null, null, null, 'Médio / raio 6m', null, 'Cria fumaça e camuflagem total.', null, null, null, null, null, null, 'Padrão', null, null, '2 rodadas', null, null, array['explosivo'], 'ordem-paranormal-cap3', true),
  (null, 'Granada incendiária', 'geral', 'explosivo', 1, 1, 1, null, null, null, null, '6d6', null, null, 'Médio / raio 6m', 'Fogo', 'Pode deixar em chamas.', null, null, null, null, null, null, 'Padrão', null, 'Reflexos DT Agi reduz', null, null, null, array['explosivo'], 'ordem-paranormal-cap3', true),
  (null, 'Algemas', 'geral', 'operacional', 0, 0, 1, null, null, null, null, null, null, null, null, null, 'Usadas para prender uma criatura agarrada ou indefesa.', null, null, null, null, null, null, null, null, 'Acrobacia DT 30 para escapar', null, null, null, array['operacional'], 'ordem-paranormal-cap3', true),
  (null, 'Corda', 'geral', 'operacional', 0, 0, 1, null, null, null, null, null, null, null, null, null, 'Rolo de 10 metros de corda resistente.', null, null, null, null, null, '+5 em Atletismo em situações apropriadas', null, null, null, null, null, null, array['operacional'], 'ordem-paranormal-cap3', true),
  (null, 'Lanterna tática', 'geral', 'operacional', 1, 1, 1, null, null, null, null, null, null, null, 'Cone 9m', null, 'Pode ofuscar um ser em alcance curto.', null, null, null, null, null, null, 'Movimento para mirar', null, null, '1 rodada', null, null, array['operacional'], 'ordem-paranormal-cap3', true),
  (null, 'Mochila militar', 'geral', 'operacional', 1, 1, 0, '*', null, null, null, null, null, null, null, null, 'Aumenta a capacidade de carga em 2 espaços.', null, null, null, null, null, null, null, null, null, null, null, null, array['operacional'], 'ordem-paranormal-cap3', true),
  (null, 'Máscara de gás', 'geral', 'operacional', 0, 0, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '+10 em Fortitude contra efeitos de respiração', null, null, null, null, null, null, array['operacional'], 'ordem-paranormal-cap3', true),
  (null, 'Componentes ritualísticos de (elemento)', 'geral', 'paranormal', 0, 0, 1, null, null, null, null, null, null, null, null, null, 'Necessários para conjurar rituais do elemento escolhido.', null, null, null, null, null, null, null, null, null, null, null, 'Escolha Sangue, Morte, Conhecimento ou Energia.', array['paranormal','ritual'], 'ordem-paranormal-cap3', true)
on conflict do nothing;
